name: Promote to Production

on:
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

jobs:
  promote:
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - name: Install Cloudsmith CLI
        run: |
          pip install cloudsmith-cli

      - name: Promote package from QA to Prod
        run: |
          cloudsmith copy \
            atulya_s/acme-pypi-qa/acme-data-utils@0.1.9 \
            atulya_s/acme-pypi-prod
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}